<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MediaDevicesUnitTest</AssemblyName>
    <RootNamespace>MediaDevicesUnitTest</RootNamespace>
    <PublishTrimmed>True</PublishTrimmed>
    <PublishAot>True</PublishAot>
    <Version>2.1.0.1000</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest" Version="4.3.3" />
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\MediaDevices80\MediaDevices80.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <Import Project="..\MediaDevicesUnitTestShare\MediaDevicesUnitTestShare.projitems" Label="Shared" />

</Project>
