name: Continuous Integration

on: 
  push:
    branches: [main,]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    environment: sign
    env:
      Solution: MediaDevices.sln
      NugetSpc: MediaDevices.nuspec
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          2.1.x
          3.1.x
          5.0.x

    - name: Set DotNetFramework
      uses: Bassman2/setup-dotnetfwk@v1
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Add SignKeys
      uses: Bassman2/SignKey@v1
      with:
        file: Bassman.snk
        key: ${{ secrets.SIGNKEY }}
        
    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1

    - name: Nuget restore dependencies
      run: nuget restore $env:Solution

    - name: Dotnet restore dependencies
      run: dotnet restore $env:Solution

    - name: MSBuild of solution
      run: msbuild $env:Solution /p:configuration="${{ matrix.build_configuration }}" /verbosity:minimal   
        
#    - name: Nuget pack nuspec
#      if: matrix.build_configuration == 'Release'
#      working-directory: .\Nuget\
#      run: nuget pack $env:NugetSpc -properties Configuration=Release
