name: Continuous Integration

permissions:
  pull-requests: write
  security-events: write
  packages: read
  actions: read
  contents: read
  
on:
  push:
    branches: [main,]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    environment: sign
    env:
      Solution: MediaDevices.slnx
      NugetSpc: MediaDevices.nuspec
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release, Debug]

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set DotNetFramework
      uses: Bassman2/setup-dotnetfwk@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v4

    - name: Add SignKeys
      uses: Bassman2/SignKey@v1
      with:
        file: Bassman.snk
        key: ${{ secrets.SIGNKEY }}

    - name: Nuget restore dependencies
      run: nuget restore $env:Solution

    - name: Dotnet restore dependencies
      run: dotnet restore $env:Solution

    - name: MSBuild of solution
      run: msbuild $env:Solution /p:configuration="${{ matrix.build_configuration }}" /verbosity:minimal

    - name: Nuget pack nuspec
      if: matrix.build_configuration == 'Release'
      working-directory: .\Nuget\
      run: nuget pack $env:NugetSpc -properties Configuration=Release
