using GeneratorLibrary;
using System.Text;

namespace FindGenerator;

partial class FinderGenerator
{
    private void CreateFindClassFieldsFile(Class cl)
    {
        StringBuilder sb = new(
            $$"""
            // <auto-generated />

            #nullable enable annotations
            #nullable disable warnings

            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618
            
            namespace {{cl.NameSpace}};

            internal static class {{cl.Name}}FindPropertyKeyName
            {

            """);

        ///////////////////////////////////////////////////////////////////////
        // get PropertyKey names
        ///////////////////////////////////////////////////////////////////////

        sb.AppendLine(
            $$"""
                public static string GetName(this Guid guid)
                {

            """);

        foreach (var field in cl.Fields)
        {
            if (field.Type.Name == "Guid")
            {
                sb.AppendLine(
                    $$"""
                            if (guid == WPD.{{field.Name}})
                            {
                                return nameof(WPD.{{field.Name}});
                            }
                
                    """);
            }
        }

        sb.AppendLine(
            $$"""
                    return $"{guid}";
                }
            """);

        ///////////////////////////////////////////////////////////////////////
        // get PropertyKey names
        ///////////////////////////////////////////////////////////////////////

        sb.AppendLine(
            $$"""
                public static string GetName(this PropertyKey propertyKey)
                {

            """);

        foreach (var field in cl.Fields)
        {
            if (field.Type.Name == "PropertyKey")
            {
                sb.AppendLine(
                    $$"""
                            if (propertyKey == WPD.{{field.Name}})
                            {
                                return nameof(WPD.{{field.Name}});
                            }
                
                    """);
            }
        }

        sb.AppendLine(
            $$"""
                    return $"{GetName(propertyKey.fmtid)}:{propertyKey.pid}";
                }
            """);

        ///////////////////////////////////////////////////////////////////////
        // class end
        ///////////////////////////////////////////////////////////////////////
        
        sb.AppendLine(
            """
            }
            """);

        AddSource($"{cl.Name}FindFields.g.cs", sb.ToString());
    }
}
