using GeneratorLibrary;
using System.Text;

namespace FindGenerator;

partial class FinderGenerator
{
    private void CreateFindEnumFieldsFile(Enum en)
    {
        StringBuilder sb = new(
            $$"""
            // <auto-generated />

            #nullable enable annotations
            #nullable disable warnings

            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618
            
            namespace {{en.NameSpace}};

            internal static class {{en.Name}}GuidFinder
            {

            """);

        ///////////////////////////////////////////////////////////////////////
        // Create Guid Fields
        ///////////////////////////////////////////////////////////////////////

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.EnumGuidAttribute");
            if (attr != null)
            {
                switch (attr.ConstructorArgumentsLength)
                {
                case 0:
                    sb.AppendLine($"    private static readonly Guid Guid{field.Name} = new Guid();");
                    break;
                case 1:
                    string guid = attr.GetConstructorArgument(0)?.ToString() ?? string.Empty;
                    sb.AppendLine($"    private static readonly Guid Guid{field.Name} = new Guid({guid});");
                    break;
                case 11:
                    uint a = attr.GetConstructorArgument(0)?.ToUInt32() ?? 0;
                    ushort b = attr.GetConstructorArgument(1)?.ToUInt16() ?? 0;
                    ushort c = attr.GetConstructorArgument(2)?.ToUInt16() ?? 0;
                    byte d = attr.GetConstructorArgument(3)?.ToByte() ?? 0;
                    byte e = attr.GetConstructorArgument(4)?.ToByte() ?? 0;
                    byte f = attr.GetConstructorArgument(5)?.ToByte() ?? 0;
                    byte g = attr.GetConstructorArgument(6)?.ToByte() ?? 0;
                    byte h = attr.GetConstructorArgument(7)?.ToByte() ?? 0;
                    byte i = attr.GetConstructorArgument(8)?.ToByte() ?? 0;
                    byte j = attr.GetConstructorArgument(9)?.ToByte() ?? 0;
                    byte k = attr.GetConstructorArgument(10)?.ToByte() ?? 0;
                    sb.AppendLine($"    private static readonly Guid Guid{field.Name} = new Guid(0x{a:x8}, 0x{b:x4}, 0x{c:x4}, 0x{d:x2}, 0x{e:x2}, 0x{f:x2}, 0x{g:x2}, 0x{h:x2}, 0x{i:x2}, 0x{j:x2}, 0x{k:x2});");
                    break;
                default:
                    sb.AppendLine($"    // EnumGuid width undefined arguments found for {field.Name}");
                    break;
                }
            }
        }

        ///////////////////////////////////////////////////////////////////////
        // Create PropertyKey Fields
        ///////////////////////////////////////////////////////////////////////

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.KeyAttribute");
            if (attr != null)
            {
                switch (attr.ConstructorArgumentsLength)
                {
                case 0:
                    sb.AppendLine($"    private static readonly PropertyKey Key{field.Name} = new PropertyKey();");
                    break;
                case 2:
                    string guid = attr.GetConstructorArgument(0)?.ToString() ?? string.Empty;
                    uint pid = attr.GetConstructorArgument(1)?.ToUInt32() ?? 0;
                    sb.AppendLine($"    private static readonly PropertyKey Key{field.Name} = new PropertyKey({guid}, {pid});");
                    break;
                case 12:
                    uint a = attr.GetConstructorArgument(0)?.ToUInt32() ?? 0;
                    ushort b = attr.GetConstructorArgument(1)?.ToUInt16() ?? 0;
                    ushort c = attr.GetConstructorArgument(2)?.ToUInt16() ?? 0;
                    byte d = attr.GetConstructorArgument(3)?.ToByte() ?? 0;
                    byte e = attr.GetConstructorArgument(4)?.ToByte() ?? 0;
                    byte f = attr.GetConstructorArgument(5)?.ToByte() ?? 0;
                    byte g = attr.GetConstructorArgument(6)?.ToByte() ?? 0;
                    byte h = attr.GetConstructorArgument(7)?.ToByte() ?? 0;
                    byte i = attr.GetConstructorArgument(8)?.ToByte() ?? 0;
                    byte j = attr.GetConstructorArgument(9)?.ToByte() ?? 0;
                    byte k = attr.GetConstructorArgument(10)?.ToByte() ?? 0;
                    pid = attr.GetConstructorArgument(11)?.ToUInt32() ?? 0;
                    sb.AppendLine($"    private static readonly PropertyKey Key{field.Name} = new PropertyKey(0x{a:x8}, 0x{b:x4}, 0x{c:x4}, 0x{d:x2}, 0x{e:x2}, 0x{f:x2}, 0x{g:x2}, 0x{h:x2}, 0x{i:x2}, 0x{j:x2}, 0x{k:x2}, {pid});");
                    break;
                default:
                    sb.AppendLine($"    // Key width undefined arguments found for {field.Name}");
                    break;
                }
            }
        }

        ///////////////////////////////////////////////////////////////////////
        // Guid? FindXxxxKey(this Xxxx value)
        ///////////////////////////////////////////////////////////////////////

        sb.AppendLine(
            $$"""

                public static Guid GetGuid(this {{en.Name}} value)
                {
                    return value switch
                    {
            """);

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.EnumGuidAttribute");
            if (attr != null)
            {
                sb.AppendLine($"            {en.Name}.{field.Name} => Guid{field.Name},");
            }
        }
        sb.AppendLine(
            $$"""
                        _ => Guid.Empty
                    };
                }
                
            """);

        ///////////////////////////////////////////////////////////////////////
        // Xxxx FindXxxxEnum(this PropertyKey value)
        ///////////////////////////////////////////////////////////////////////


        sb.AppendLine(
            $$"""
                public static {{en.Name}} Find{{en.Name}}Enum(this Guid value)
                {
            """);

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.EnumGuidAttribute");
            if (attr != null)
            {
                sb.AppendLine(
                $$"""
                        if (value == Guid{{field.Name}})
                        {
                            return {{en.Name}}.{{field.Name}};
                        }
                """);
            }
        }
        sb.AppendLine(
            $$"""
                    return {{en.Name}}.Unknown;
                }
            
            """);

        ///////////////////////////////////////////////////////////////////////
        // string FindXxxxName(this Guid value)
        ///////////////////////////////////////////////////////////////////////

        sb.AppendLine(
            $$"""
            
                public static string Find{{en.Name}}Name(this Guid value)
                {
            """);

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.EnumGuidAttribute");
            if (attr != null)
            {
                sb.AppendLine(
                $$"""
                        if (value == Guid{{field.Name}})
                        {
                            return "{{field.Name}}";
                        }
                """);
            }
        }

        sb.AppendLine(
            $$"""
                    return "Unknown";
                }
            """);

        ///////////////////////////////////////////////////////////////////////
        // PropertyKey? FindXxxxKey(this Xxxx value)
        ///////////////////////////////////////////////////////////////////////

        sb.AppendLine(
            $$"""

                public static PropertyKey? Find{{en.Name}}Key(this {{en.Name}} value)
                {
                    return value switch
                    {
            """);

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.KeyAttribute");
            if (attr != null)
            {
                sb.AppendLine($"            {en.Name}.{field.Name} => Key{field.Name},");
            }
        }

        sb.AppendLine(
            $$"""
                        _ => null
                    };
                }
                
            """);

        ///////////////////////////////////////////////////////////////////////
        // Xxxx FindXxxxEnum(this PropertyKey value)
        ///////////////////////////////////////////////////////////////////////


        sb.AppendLine(
            $$"""
                public static {{en.Name}} Find{{en.Name}}Enum(this PropertyKey value)
                {
            """);

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.KeyAttribute");
            if (attr != null)
            {
                sb.AppendLine(
                $$"""
                        if (value == Key{{field.Name}})
                        {
                            return {{en.Name}}.{{field.Name}};
                        }
                """);
            }
        }
        sb.AppendLine(
            $$"""
                    return {{en.Name}}.Unknown;
                }

            """);

        ///////////////////////////////////////////////////////////////////////
        // string FindXxxxName(this PropertyKey value)
        ///////////////////////////////////////////////////////////////////////


        sb.AppendLine(
           $$"""
                public static string Find{{en.Name}}Name(this PropertyKey value)
                {
            """);

        foreach (var field in en.Fields)
        {
            var attr = field.GetAttribute("MediaDevices.Internal.KeyAttribute");
            if (attr != null)
            {
                sb.AppendLine(
                $$"""
                        if (value == Key{{field.Name}})
                        {
                            return "{{field.Name}}";
                        }
                """);
            }
        }

        sb.AppendLine(
            """
                    return "Unknown";
                }
            """);

        ///////////////////////////////////////////////////////////////////////
        // End
        ///////////////////////////////////////////////////////////////////////

        sb.AppendLine(
            """
            }
            """);

        AddSource($"{en.Name}FindFields.g.cs", sb.ToString());
    }
}
